server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    username: root@localhost
    password:

  jpa:
    properties:
      hibernate:
       gi dialect: org.hibernate.dialect.MySQLDialect